---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfmbingogame
  labels:
    app: tfmbingogame
    author: estherterrero
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tfmbingogame
      author: estherterrero
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: tfmbingogame
        author: estherterrero
    spec:
      containers:      
      - name: tfmbingogame
        image: a784d6614237:v1
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: tfmbingogame
  labels:
    app: tfmbingogame
    author: estherterrero
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: tfmbingogame
    author: estherterrero
  type: ClusterIP
